### PR TITLE
Remove analytics, custom server support, custom branding and more

### PR DESCRIPTION
**Pull request by vantezzen**
Hello,
I have recently forked this repository and made some changes to it.
If you want to, we can merge these changes into your repository, otherwise I would continue developing on my own repository independently.

Changes made:
- Removed Franz/Google Analytics
- Make all users premium (as suggested in #15)
- Remove redirection to pricing and invitation page after signup
- Replace "Franz" with "Ferdi" in the UI
- Create a custom logo for Ferdi (https://github.com/vantezzen/ferdi/blob/master/src/assets/images/logo.svg)
- Replace images with custom images for Ferdi
- Remove "Franz is better together"(shareFranz) popup
- Add support for custom Franz servers (for usage with https://github.com/vantezzen/ferdi-server) 
- Add information about development to the README
- Add all-contributors to README
- Fix security issues from dependencies using `npm audit fix`

### CODE REVIEW

**Comment by kytwb** [comment]
@vantezzen happy to merge, LGTM! 👍

**Comment by kytwb** [comment]
Awesome contribution @vantezzen, will review soon! 🙏 Thank you!

**Comment by kytwb** [comment]
Takes care of https://github.com/kytwb/ferdi/issues/2 as well.

**Comment by vantezzen** [comment]
Thanks, I will add a mention to ferdi-server.
I am currently testing for errors and am working on a feature for ferdi-server to import Franz accounts, will remove the WIP as soon as I am done.

Just thinking about custom servers: Do you think Ferdi should default to a custom ferdi-server to improve features (e.g. Premium for everybody*) or keep the Franz server (api.franzinfra.com) as the default server to improve compatibility?

*I have made everyone Premium in the Ferdi app, but some features (e.g. workspaces) are still restricted through the server if the user is not premium.

**Comment by kytwb** [comment]
I'm ok with keeping the Franz server for now; so far, people using Ferdi were not Premium afaik, so we can keep enhancing the premium features handling as we go.

**Comment by AGCaesar** [comment]
Thanks for all the great work! Any idea when the pull request will be merged?

**Comment by kytwb** [comment]
@AGCaesar waiting for @vantezzen confirmation 🙏

**Comment by vantezzen** [comment]
Should be very soon, I am currently testing if all features can be used with a custom ferdi-server. Expecting to be done today or tomorrow.

**Comment by vantezzen** [comment]
PR can be merged now, all CI checks and builds just passed.

I have now tested Ferdi with the official Franz server and custom ferdi-servers and everything seems to work. If you want to, you can also do some tests before rolling out the new version, I set up a public demo of ferdi-server at <https://ferdi.vantezzen.io> (that also includes some custom recipes) which can be used for testing.

I have bumped the version number from 5.2.0 to 5.3.0.

This PR will also fix #2 #6 and #15.

I have not yet included a fix for #5 as it requires some rewriting of the way Ferdi stores services and workspaces. Ferdi doesn’t save this information itself but rather relies on getting it from the server on every start. I might create another PR later if you aren’t working on a fix already.

**Comment by kytwb** [comment]
[Ferdi-5.3.0](https://github.com/kytwb/ferdi/releases/tag/Ferdi-5.3.0) has been released! 🎉

**Comment by vantezzen** [comment]
It looks like v5.3.0 has some difficulties with the WhatsApp recipe. The recipe solves the "WhatsApp works with Google Chrome 49+" by removing the "Franz" from the user agent (https://github.com/meetfranz/recipe-whatsapp/blob/979776457c92ccc915a0084bb190129a7be37aa0/index.js#L3), but this PR replaced Franz with Ferdi

**Pull request merged**
